# Hyperparameters
BATCH_SIZE = 16  # Not explicitly mentioned in the article
EPOCHS = 20
PATIENCE = 3
LEARNING_RATE = 0.01  # Initial learning rate as mentioned in the (newest) article
# ADD LR DECAY!!
LEARNING_RATE_DECAY_EPOCHS = 5  # not mentioned, check it
MODEL_SAVE_DIR = "models/saved/"    # Model save path base directory

