# Hyperparameters
BATCH_SIZE = 16  # Not explicitly mentioned in the article
EPOCHS = 20
PATIENCE = 3
LEARNING_RATE = 0.01  # Initial learning rate as mentioned in both articles
LEARNING_RATE_DECAY_FACTOR = 0.0005 # mentioned in first article 
LEARNING_RATE_DECAY_EPOCHS = 1  # not mentioned, so assuming that lr decay is performed through each epoch
MOMENTUM = 0.9  # used in first article
MODEL_SAVE_DIR = "models/saved/"    # Model save path base directory

