# Hyperparameters
batch_size: 16   # Not explicitly mentioned in the article
epochs: 20
patience: 3
learning_rate: 0.001    # Initial learning rate as mentioned in both articles
learning_rate_decay_factor: 0.0005   # mentioned in first article
learning_rate_decay_epochs: 1    # not mentioned, so assuming that lr decay is performed through each epoch
momentum: 0.9    # used in first article

window_sizes:    # window sizes to be used for grids
  - [small, 2.5]
  - [medium, 5.0]
  - [large, 10.0] 

features_to_use: ['intensity', 'R', 'G' , 'B' ,'nvi' ,'ndwi']  # features to be used for training
num_classes: 5  # number of classes. Needed only if raw data does not exist and we're using already generated feature imgs. Otherwise it will be automatically computed from raw data.

# -- (!) -- note: features to use include only the additional features, meaning that x,y,z are always already included and not counted in the channels -------- 


# User options
models_save_dir: "models/saved/"      # Model save path base directory
save_model: false    # whether to save the model or to discard. Default is False, i.e., discard the trained model.
raw_data_filepath: "data/raw/features_F.las"   # directory where raw data (to be eventually processed) is stored
load_model: false # whether to use an already trained model for inference or not
load_model_filepath : "models/saved/mcnn_model_20240922_231624.pth" # file path to the model to load for inference

