# Hyperparameters
batch_size: 32   # Not explicitly mentioned in the article
epochs: 10
patience: 3
learning_rate: 0.01    # Initial learning rate as mentioned in both articles
learning_rate_decay_factor: 0.5   # mentioned in first article as 0.0005
learning_rate_decay_epochs: 5    # not mentioned
momentum: 0.9    # used in first article
num_workers : 0  # number of workers for parallel processing

dataset_filepath : 'data/datasets/sampled_full_dataset/sampled_data_5251681.csv'   # File path to the full dataset file
training_data_filepath : "data/training_data/21/train_21.csv"   # File path to training data (subset of full dataset)

window_sizes:    # window sizes to be used for grids
  - [small, 2.5]
  - [medium, 5.0]
  - [large, 10.0] 

features_to_use: ['intensity', 'red', 'green' , 'blue' ,'nvi' ,'ndwi']  # features to be used for training

# -- (!) -- NOTE: features_to_use include only the additional features, meaning that x,y,z are always read from data, but they are not included in the channels
# -- (!) -------  this is because x,y,z are employed in the grids' features assignment (through nearest neighbour search), but are not assigned as features to the grids

model_save_dir: "models/saved/"   # Directory where the model is to be saved after training
save_model: true    # whether to save the model or to discard. Default is False, i.e., discard the trained model.

evaluate_model_after_training : false    # whether to evaluate the model after training it
perform_evaluation : false  # wetheer to evaluate a loaded model
evaluation_data_filepath : "data/training_data/21/test_21.csv"  # file path to the evaluation dataset (subset of full data)

predict_labels: false  # wether to predict labels on an input file or not
file_to_predict: "data/chosen_tiles/" # file path to the file whose label we need to predict 

load_model_filepath : "models/saved/mcnn_model_20240922_231624.pth"   # file path to the model to load for inference




