name: CNNLidar
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.0  
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - tqdm
  - yaml
  - pip
  - pip:
      - matplotlib  
      - open3d      
